# Generated by Django 3.2.8 on 2021-12-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211106_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='курс валюты')),
                ('rate_update_at', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
            ],
        ),
    ]
