# Generated by Django 3.2.8 on 2021-11-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ключ активации'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activation_key_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
