# Generated by Django 3.2.8 on 2021-11-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_shopuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'М'), ('W', 'Ж'), ('O', 'Не указан')], default='O', max_length=1, verbose_name='пол'),
        ),
    ]
