# Generated by Django 3.2.8 on 2021-11-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_shopuserprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на аватарку'),
        ),
    ]
